### ISSUE TITLE
Add a GitHub Workflow that will automatically publish a Model to DAFNI

### ISSUE THREAD

**Issue by roseDickinson** [OpenCLIM/udm-dafni#1]

**Comment by fmcclean** [comment]
Ideally, this could be an action available on GitHub Marketplace so that other projects can make use of it.

Linked to https://github.com/dafnifacility/user-feedback/issues/8

**Comment by roseDickinson** [comment]
Completed as part of https://github.com/OpenCLIM/udm-dafni/pull/6
