### ISSUE TITLE
Create UDM Setup/Pre-processing Model

### ISSUE THREAD

**Issue by roseDickinson** [OpenCLIM/udm-dafni#4]
- [ ] Expose parameters on main UDM Model
- [ ] Expose addition data-based parameters via pre-processing Model
- [ ] Containerise pre-processing Model
- [ ] Write Model Definition
- [ ] Upload pre-processing Model to DAFNI

**Comment by Craig-Robson** [comment]
https://github.com/geospatialncl/udm-setup

**Comment by Craig-Robson** [comment]
Done
