### ISSUE TITLE
move data into correct dir structure

### ISSUE THREAD

**Issue by Craig-Robson** [OpenCLIM/udm-dafni#8]
UDM expects all data in the same DIR, though data stored on DAFNI will be in independent DIRS, so will need to move/copy into the correct location before running UDM

**Comment by fmcclean** [comment]
Ah, I didn’t realise. Do you want me to set this up? Is every file going to be from an independent dataset?

**Comment by fmcclean** [comment]
I was under the impression that udm-setup was going to pull all the input files into a single directory. The input dataslot is currently required but it shouldn’t be as the data may come from a previous step.

**Comment by Craig-Robson** [comment]
now in UDM-setup
